FROM openjdk:11.0.5-jdk as builder

WORKDIR /code
COPY *.gradle gradle.* gradlew ./
COPY gradle ./gradle
RUN ./gradlew build || return 0

COPY src/ src/

# Alternatively ...
# RUN ./gradlew resolveDependencies

RUN ["./gradlew", "-q", "--no-daemon"]
